version: 2

sources:
  - name: raw
    database: gravity-infra
    schema: gravity
    tables:
      - name: scheduler_run_log
        description: "Source of data for gravity runs."
      - name: truedash_conf_resources
      - name: truedash_conf_datatargets
      - name: truedash_conf_datasources
      - name: Orgs
        description: "details about organisations"
      - name: MongoStripe
        description: "stripe data about subscriptions"
      - name: Users
        description: "details about users"
      - name: UsersLoginHistory
        description: "details about user login events"