version: 2

sources:
  - name: raw
    database: gravity-infra
    schema: gravity
    tables:
      - name: DE_Scheduler_Run_Log
        description: "Source of data for gravity runs."
      - name: truedash_conf_resources
      - name: truedash_conf_datatargets
      - name: truedash_conf_datasources